### ISSUE TITLE
Ask for Livox mid-360 dataset 

### ISSUE THREAD

**Issue by coldbath** [KTH-RPL/dufomap#1]
Hi Dr.Zhang

Recently, I have been researching SLAM based on Livox mid-360, and very interested in your research.
I wonder could you share the dataset
[Indoor-Floor] Our own dataset, Collected by Livox mid-360 in a quadruped robot.

Thank you very much for considering my request. I look forward to your prompt response.

Best regards,

Cino

**Comment by Kin-Zhang** [comment]
Data released, please download through or check [the download page](https://zenodo.org/records/10886629):

```bash
wget https://zenodo.org/records/10886629/files/twofloor.zip
```
