### ISSUE TITLE
哈喽哈喽，我最近想在一个ros2项目中使用dufomap，但是我一旦引入ros2相关头文件，就会引发一串编译错误：

### ISSUE THREAD

**Issue by whw-create** [KTH-RPL/dufomap#11]
哈喽哈喽，我最近想在一个ros2项目中使用dufomap，但是我一旦引入ros2相关头文件，就会引发一串编译错误：
![图片](https://github.com/user-attachments/assets/f269827a-c5eb-4a70-b9b1-fc66756d92f1)
有没有碰到过类似的问题呢

_Originally posted by @whw-create in https://github.com/KTH-RPL/dufomap/issues/10#issuecomment-2249212106_

**Comment by Kin-Zhang** [comment]
没遇到过哎，可能需要提供你环境信息，或者一个可复现问题的docker image，我可以后续看一下

**Comment by whw-create** [comment]
我查到的应该是版本问题，因为我同时包含的头文件有20的新特性和已经被20抛弃的旧特性，然后一编就g

**Comment by Kin-Zhang** [comment]
那只能分开package编译了，我也没试过ros2里的编译

**Comment by Kin-Zhang** [comment]
我更新了dufomap python 的库，现在你可以直接新建一个Python node import dufomap就行；应该就没有这个编译问题了
