### ISSUE TITLE
调参

### ISSUE THREAD

**Issue by zuixiaosanlang** [KTH-RPL/dufomap#13]
数据集下载链接：
通过网盘分享的文件：pcd.zip
链接: https://pan.baidu.com/s/1BjD-2Dl5RjiAsPFNqOsSsQ 提取码: xvyh 

总体滤除效果还是很优秀的，想看看，针对我这样的数据集，是不是还可以调哪些参数可以更好

1）默认参数，我把动态点云保存下来这样的效果：
![image](https://github.com/user-attachments/assets/730b6804-29b6-487f-b4d8-53d196a49fcc)

这个地方，去得不是很干净，静态点云中还有不少悬浮点

2）这三个参数我尝试修改过
![image](https://github.com/user-attachments/assets/51b2f836-d3b5-4306-b99d-3068a0a5b360)

**Comment by Kin-Zhang** [comment]
![image](https://github.com/user-attachments/assets/378ea278-b3ae-4bfd-8683-cb99435a0058)

我看了一下数据，和你想要的应该是更aggressive一点的clean map，所以我调了这两个参数，得到的结果大概是这样的，你指出的地方，我这版运行 只有紧贴地面的点有残留（几乎和地面持平），还有一个角落有一点漂浮的点（如果介意可以在map层面 再用一个noise filter

![image](https://github.com/user-attachments/assets/60566d51-197d-4b74-a16d-8332196fdb2e)


Parameters:

![image](https://github.com/user-attachments/assets/5f30bb7d-9e09-4c71-9c92-757dfda60c90)
