### ISSUE TITLE
Questions about Python API

### ISSUE THREAD

**Issue by RickyYXY** [KTH-RPL/dufomap#14]
I found that in your SeFlow project, you used dufomap like this
`mydufo = dufomap(0.2, 0.2, 1, num_threads=12) # resolution, d_s, d_p, hit_extension`
`mydufo.setCluster(0, 20, 0.2) # depth=0, min_points=20, max_dist=0.2`
I want to know what the _depth=0, min_points=20, max_dist=0.2_ means. Why depth=0?

Thks!

**Comment by Kin-Zhang** [comment]
depth=0 means use voxel=0.2, it's about octree, if you want you can check the code detail on octree part.

**Comment by Kin-Zhang** [comment]
I update main.py script for DUFOMap task now. Feel free to check: https://github.com/KTH-RPL/dufomap/blob/main/main.py
