### ISSUE TITLE
static areas remove too much

### ISSUE THREAD

**Issue by coldbath** [KTH-RPL/dufomap#3]
Hi Dr.Zhang

First of all, thank you for sharing the data. I have run **_dufomap_**  with  **_twofloor_**  and **_our own data_** and found that static areas such as floors and walls will also be remove, which with configs in assets/.

I did not find this phenomenon on **_Octomap_**, but the running time is very slow

Can this phenomenon be optimized by adjusting parameters?

Here is the screenshots, run with _**twofloor**_:

_**dufomap_output_dynamic.pcd**_
![lQDPKHz13-zXEF3NA0XNBW6wWrCHyUfKrPQGFCp5rPwoAA_1390_837](https://github.com/KTH-RPL/dufomap/assets/20087254/5bde48c0-0d4d-4ae9-bf1b-6dca010f127a)

**_dufomap_output_static.pcd_**
![lQDPJwrp0MccB13NA0XNBZCwUjSqZzgmMRQGFCqHv8pOAA_1424_837](https://github.com/KTH-RPL/dufomap/assets/20087254/408a4a87-3374-44db-98d1-67ebf67479dc)

**_octomapfg_output.pcd_**
![lQDPJwolXW7pV13NAz3NBY2wPJGAMn0E0B0GFCqdmLrTAQ_1421_829](https://github.com/KTH-RPL/dufomap/assets/20087254/08455aaa-7eb3-4d81-a154-a2bffd2a9036)

Best regards,

Cino

**Comment by Kin-Zhang** [comment]
could you run the code version in this repo?

**Comment by coldbath** [comment]
This is the result of this repo, and the phenomenon is similar
![lQDPJwFo6uiFBv3NAy3NBeGw1r1_i457pD8GFDXCi5STAA_1505_813](https://github.com/KTH-RPL/dufomap/assets/20087254/880fefe2-40f5-444a-89bd-d73b0bfd32d2)
![1713865928827](https://github.com/KTH-RPL/dufomap/assets/20087254/ec6bbba7-06ff-44ee-9f54-7ad1a37aa85a)

**Comment by coldbath** [comment]
> could you run the code version in this repo?

This is the result of  this repo, and the phenomenon is similar
![lQDPJwFo6uiFBv3NAy3NBeGw1r1_i457pD8GFDXCi5STAA_1505_813](https://github.com/KTH-RPL/dufomap/assets/20087254/3872efbe-cf6d-45ae-bcfa-5a4dee4f660b)
![1713865928827](https://github.com/KTH-RPL/dufomap/assets/20087254/15e315b2-8103-49ad-bb1e-e966f8660f12)

**Comment by Kin-Zhang** [comment]
Don't know why your result is different, but here is the one I run just now through the repo:
![image](https://github.com/KTH-RPL/dufomap/assets/35365764/3b3cf9c2-84c1-4281-b72f-01436755ed54)
![image](https://github.com/KTH-RPL/dufomap/assets/35365764/6f53caee-8112-4b48-b304-80930a43754f)


And here is the paper effect (no quantitative but qualitative): it's actually have some holes (the reason is because localization error and ground could be heavy)
![image](https://github.com/KTH-RPL/dufomap/assets/35365764/40b2e22e-1f6f-472d-929f-986ace5b61d3)

if possible could you provide your `uname -a` and `lscpu`?

**Comment by coldbath** [comment]
> Don't know why your result is different, but here is the one I run just now through the repo: ![image](https://private-user-images.githubusercontent.com/35365764/324831123-3b3cf9c2-84c1-4281-b72f-01436755ed54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU5MDMsIm5iZiI6MTcxMzg3NTYwMywicGF0aCI6Ii8zNTM2NTc2NC8zMjQ4MzExMjMtM2IzY2Y5YzItODRjMS00MjgxLWI3MmYtMDE0MzY3NTVlZDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOWZmOTU0OTc1MjU1NDk3ZjRiNmY2NmIzNzFiZWQyYmFkNzZlNjA4OTdkZDk2MDhmMzYyYWU3MDhhNmY3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bVYJ_FvUgDS5lrT-UqmhvMtlzXu5OheczobC_PGlhKs) ![image](https://private-user-images.githubusercontent.com/35365764/324831411-6f53caee-8112-4b48-b304-80930a43754f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU5MDMsIm5iZiI6MTcxMzg3NTYwMywicGF0aCI6Ii8zNTM2NTc2NC8zMjQ4MzE0MTEtNmY1M2NhZWUtODExMi00YjQ4LWIzMDQtODA5MzBhNDM3NTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ODk5YjczYmY1MmVjMjI2ZWJlYzRhMGI0ZTMyNzgzYjhhNWUzZDljMGYyZTk3NTRhMjIwNmFjOTA4Y2UxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1FcVMmqNV8VdBH4wFikoSZky8S9UmWQsc3GDJM-b1w)
> 
> And here is the paper effect (no quantitative but qualitative): it's actually have some holes (the reason is because localization error and ground could be heavy) ![image](https://private-user-images.githubusercontent.com/35365764/324830503-40b2e22e-1f6f-472d-929f-986ace5b61d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzU5MDMsIm5iZiI6MTcxMzg3NTYwMywicGF0aCI6Ii8zNTM2NTc2NC8zMjQ4MzA1MDMtNDBiMmUyMmUtMWY2Zi00NzJkLTkyOWYtOTg2YWNlNWI2MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhODBhMDYwNWVmODg0NGY2MzZkZGEyNzU1NzRjNjlkMjE1MzA4ZTgwNGM5ZjBhNjcwZjlmYjJjYTRiNjExY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W3c1_0iOu4jAS2V0C6U95OVxNy2IQYE6bX4L7jJeae8)
> 
> if possible could you provide your `uname -a` and `lscpu`?

![lQDPJx5akj65fw02zQLWsBkYv8hVvSc3BhRaPi4reQA_726_54](https://github.com/KTH-RPL/dufomap/assets/20087254/eed09ba4-bba7-48d3-a149-ade5e3bdc060)
![1713875470283](https://github.com/KTH-RPL/dufomap/assets/20087254/28c253d4-fb7e-4cfc-a386-c6e0dadb2be8)

**Comment by coldbath** [comment]
> didn't see any problem with your system and CPU info.
> 
> Could you again git pull, check [config](https://github.com/KTH-RPL/dufomap/blob/main/assets/config.toml) and run again with the latest commit? There are holes but as I attached from my side, should that much (the config file) or uncomment this line: [`std::cout<<config;`](https://github.com/KTH-RPL/dufomap/blob/main/dufomap.cpp#L359) and screenshot when you run the code.
> 
> Let us know if you still have problem with latest commit.

Previously, I downloaded the code directly, but this time I git clone the code. Perhaps this is the reason why the code is not the latest version.

I got the same result as you,  **_56318352 points_** (before is **_44021782 points_**).

Although there are still exist some holes,  maybe **_the reason is because localization error and ground could be heavy_** as you say.

I will continue to collect more data by livox-360 and test it. If there are any issues, I will provide feedback to you.

THX.

![1713922491403](https://github.com/KTH-RPL/dufomap/assets/20087254/86d6bd53-1645-44b6-a8e9-534823e62747)

![lQDPJxi2SwaDgWXNAxHNBPSwdY6VPhB8rRQGFRLslOM3AA_1268_785](https://github.com/KTH-RPL/dufomap/assets/20087254/bf67440b-01ea-41e2-a923-73df30e4d068)

**Comment by Kin-Zhang** [comment]
Great, also feel free to pull request if you want to contribute data. 

one more word, for why octomap w GF doesn't have many holes mainly because it did ground segmentation as an independent step only on a single frame (The disadvantage of ground seg is that needed tune parameters for a different setup.)

Looks like the problem already was solved. open a new one if you have other questions.
