### ISSUE TITLE
Ask for Leica-RTC360 dataset

### ISSUE THREAD

**Issue by nuo-1** [KTH-RPL/dufomap#6]
Hi Dr.Zhang
I have tested the Teaser data (KITTI 00: 384.4Mb) you provided and the results are very good. 
Now I plan to test the Leica RTC360 data and see how this algorithm performs in dense crowds. 
Can you provide me with this dataset you are using.
Thanks.

**Comment by Kin-Zhang** [comment]
All datasets can be downloaded here: https://zenodo.org/records/10886629. Reference to detail page: https://github.com/KTH-RPL/DynamicMap_Benchmark?tab=readme-ov-file#dataset--scripts

For Leica RTC360 is:
```bash
wget https://zenodo.org/records/10886629/files/kthcampus.zip
```
