### ISSUE TITLE
The dynamic and static maps obtained using the kitti dataset are not accurate.

### ISSUE THREAD

**Issue by DGCHAO** [KTH-RPL/dufomap#9]
Using the kitti dataset and the default configuration gave poor results.

This is a dynamic point cloud, which considers the ground to be dynamic.
![out_move](https://github.com/KTH-RPL/dufomap/assets/41352460/3db319ce-70e8-42b4-98ba-7696b896d3b0)

Below is a static point cloud.
![out_static](https://github.com/KTH-RPL/dufomap/assets/41352460/71a0fc83-013c-4cb9-b349-4f79d156d25d)

**Comment by Kin-Zhang** [comment]
Our task is to remove dynamic points. Here is a more visible clean map compared to the ground truth.
![image](https://github.com/KTH-RPL/dufomap/assets/35365764/eabc9c1a-350f-4461-a1b2-1ba5056e16a5)

If you are looking to detect dynamic objects correctly on the object level. You may want to search for object detection.
